name: VMware Event Router Build Verification

# triggered on every PRs to verify builds but only when changes inside
# vmware-event-router (sub)dir(s)
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'vmware-event-router/**'
  schedule:
  # runs daily
  - cron: '0 0 * * *'

# run all jobs with these defaults, unless specified otherwise
defaults:
  run:
    shell: bash
    working-directory: ./vmware-event-router

jobs:
  binaries:
    name: Build binaries
    strategy:
      matrix:
        go-version: ["1.19"]
        platform: ["ubuntu-latest"]

    runs-on: ${{ matrix.platform }}
    timeout-minutes: 20

    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: vmware-event-router/go.sum
        id: go
        
      - name: GoReleaser Snapshot
        uses: goreleaser/goreleaser-action@9ed2f89a662bf1735a48bc8557fd212fa902bebf
        with:
          version: latest
          args: release --clean --snapshot
          workdir: vmware-event-router
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Archive run artifacts
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882
        with:
          name: dist
          path: |
            vmware-event-router/dist/router_linux_*.tar.gz
            vmware-event-router/dist/checksums.txt
          retention-days: 1

  image:
    name: Verify Release ko artifact (no upload)
    strategy:
      matrix:
        go-version: ["1.19"]
        platform: ["ubuntu-latest"]

    runs-on: ${{ matrix.platform }}
    timeout-minutes: 20

    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        
      - name: Setup ko
        uses: ko-build/setup-ko@3aebd0597dc1e9d1a26bcfdb7cbeb19c131d3037

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: vmware-event-router/go.sum
        id: go
        
      - name: Get short COMMIT and TAG
        run: |
          echo "KO_COMMIT=$(echo -n $GITHUB_SHA | cut -c -8)" >> $GITHUB_ENV
          echo "KO_TAG=$(basename "${{ github.ref }}")" >> $GITHUB_ENV
          
      - name: Build image (no push)
        run: |
          # build, push and create release YAML
          ko resolve --platform=linux/arm64,linux/amd64 --push=false --tags ${KO_TAG},${KO_COMMIT},latest -BRf deploy/event-router-k8s.yaml > release.yaml

      - name: Archive run artifacts
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882
        with:
          name: release
          path: |
            ./vmware-event-router/release.yaml
          retention-days: 1
