name: VMware Event Router Linting

# triggered on every push and PRs but only when changes inside
# vmware-event-router (sub)dir(s)
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "vmware-event-router/**"
  push:
    paths:
      - "vmware-event-router/**"

jobs:
  golangci:
    name: lint
    strategy:
      matrix:
        go-version: ["1.19"]
        platform: ["ubuntu-latest"]

    runs-on: ${{ matrix.platform }}
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a
        with:
          go-version: ${{ matrix.go-version }}
          cache: false # use golangci-lint caching
        id: go

      - name: golangci-lint
        uses: golangci/golangci-lint-action@971e284b6050e8a5849b72094c50ab08da042db8
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: latest

          # Optional: working directory, useful for monorepos
          working-directory: vmware-event-router

          # Optional: golangci-lint command line arguments.
          args: --build-tags unit,integration -v --timeout 3m

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true
